furnapp/urls.py
from django.urls import path,reverse_lazy
from django.conf.urls.static import static
from furnapp import views
from django.contrib.auth.views import LoginView,LogoutView
from .forms import CustomLoginForm,UserPasswordResetForm
from django.contrib.auth import views as auth_views
from django.conf import settings

app_name='furnapp'

urlpatterns = [
    
    path('', views.home,name="main"),
    
    
    path('products/', views.products,name="product"),
    path('about/', views.about,name="aboutus"),
    path('contact/', views.contact,name="contact"),
    path('product-details/<str:product_name>/', views.productsdet,name="productsdet"),
    path('cart/', views.cart,name="cart"),
    path('checkout/', views.checkout,name="checkout"),
    path('updateitem/', views.update_item,name="updateitem"),
    path('process_order/', views.processorder,name="process_order"),
    path('search',views.search,name="search"),
    path('category/<str:category_n>/',views.category,name="category"),
     
    
    path('register/', views.register,name="register"),
    path('login/',LoginView.as_view(template_name="furnapp/login.html",form_class=CustomLoginForm),name="login"),
    path('logout/',LogoutView.as_view(),name='logout'),
     
     path('reset_password/',auth_views.PasswordResetView.as_view(template_name="furnapp/password_reset.html",
        form_class=UserPasswordResetForm,success_url=reverse_lazy('furnapp:password_reset_done')),
        name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="furnapp/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="furnapp/password_reset_form.html",success_url=reverse_lazy('furnapp:password_reset_complete')), 
     name='password_reset_confirm'),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="furnapp/password_reset_done.html"), 
        name="password_reset_complete"),
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

furniture/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('furnapp.urls'))
]

furnapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class customer(models.Model):

    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    email_id = models.CharField(max_length=100, null=True)
    name = models.CharField(max_length=50, null=True)

    def __str__(self):
        return str(self.name)


class order(models.Model):

    customer_id = models.ForeignKey(customer, on_delete=models.CASCADE, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id=models.CharField(max_length=100, null=True)
    #Status= (('accepted','accepted'),('not accepted','not accepted'),('delivered','delivered'),('on process','on process'))
    #status=models.CharField(max_length=20,null= True,choices=Status,blank=True)
    # delivery_address=models.CharField(max_length=100,null=True,blank=True)
    # total_bill=models.IntegerField(null=True,blank=True)
    # order_num=models.AutoField(default=0)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.ordered_item_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_item_total(self):
        orderitems = self.ordered_item_set.all()
        total = sum([item.quantity for item in orderitems])
        if(total > 0):
            return total
        else:
            return 0

    @property
    def get_total_with_del(self):

        total = self.get_cart_total
        total += 50
        return total


class shipping(models.Model):

    customer = models.ForeignKey(
        customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(order, on_delete=models.SET_NULL, null=True)
    contact_no = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=200,null=True)
    city = models.CharField(max_length=100, null=True)
    country = models.CharField(max_length=100, null=True)
    zipcode = models.IntegerField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str(self.customer)


class category(models.Model):
    category_name = (('sofa', 'sofa'), ('bed', 'bed'), ('chair', 'chair'), ('tables', 'tables'), ('wardrobe', 'wardrobe'),
                     ('lightning', 'lightning'))
    category = models.CharField(
        max_length=20, null=True, choices=category_name)

    def __str__(self):
        return self.category


class product(models.Model):
    product_id = models.CharField(max_length=200, null=True, unique=True)
    title = models.CharField(max_length=50, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    description = models.CharField(max_length=200, null=True)
    image = models.ImageField(null=True, blank=True)
    quantity = models.IntegerField(null=True)
    category = models.ForeignKey(
        category, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class ordered_item(models.Model):
    order_number = models.ForeignKey(order, on_delete=models.CASCADE)
    product_id = models.ForeignKey(product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.order_number)

    @property
    def get_total(self):
        total = self.product_id.price*self.quantity
        return total
class review(models.Model):
    Product = models.ForeignKey(product, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200, null=True)
    name=models.CharField(max_length=200, null=True)
    email=models.EmailField(max_length=200,null=True)
    date_enter=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

class cart(models.Model):
    product_id = models.ManyToManyField(product)
    customer_id = models.ForeignKey(customer, on_delete=models.CASCADE)
    total_price = models.IntegerField(default=0, blank=True)
    quantity = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return str(self.customer_id)
class contact(models.Model):
    message = models.CharField(max_length=200, null=True)
    name=models.CharField(max_length=200, null=True)
    email=models.EmailField(max_length=200,null=True)
    subject=models.CharField(max_length=200,null=True)
    date_enter=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

furnapp/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm,PasswordResetForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from .models import *

class CreateUserForm(UserCreationForm):
    class Meta:
        model= User
        fields =['username','email','password1','password2']
class CustomLoginForm(AuthenticationForm):
	username = UsernameField(
		label='',
		widget=forms.TextInput(attrs={'class':'form-control,h1','placeholder':'Username'})
	)
	password=forms.CharField(
		label="",
		strip=False ,
		widget=forms.PasswordInput(attrs={'class':'form-control,h1','placeholder':'Password'}),
	)

class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
    	super(UserPasswordResetForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={
        'class':'form-control,h1',
        'placeholder': 'Email Address',
        'type': 'email',
        'name': 'email'
        }))


class orderform(ModelForm):
	class Meta:
		model= cart
		fields =['product_id','quantity','customer_id']

class commentform(ModelForm):
	class Meta:
		model=review
		fields=['name','email','comment']
		widgets={
            'name':forms.TextInput(attrs={'class':'form-control h1','placeholder':'Name','style':'height:40px;font-size:18px;color:black;border:1px solid coral;'}),
			'email':forms.TextInput(attrs={'class':'form-control h1','placeholder':'Email','style':'height:40px;font-size:18px;color:black;border:1px solid coral;'}),
			'comment':forms.Textarea(attrs={'class':'form-control h1','placeholder':'Review','style':'height:40px;font-size:18px;color:black;border:1px solid coral;'})
		}

class contactform(ModelForm):
	class Meta:
		model=contact
		fields=['name','email','message']
		widgets={
            'name':forms.TextInput(attrs={'class':'form-control h1','placeholder':'Name','style':'height:40px;font-size:18px;color:black;border:1px solid coral;'}),
			'email':forms.TextInput(attrs={'class':'form-control h1','placeholder':'Email','style':'height:40px;font-size:18px;color:black;border:1px solid coral;'}),
			'message':forms.Textarea(attrs={'class':'form-control h1','placeholder':'Message','style':'height:40px;font-size:18px;color:black;border:1px solid coral;'})
        }

furnapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
import json
import datetime
from .models import *
from .forms import *
from .utils import *

# Create your views here.


def home(request):
    data=cartdata(request)
    cartitems=data['cartitems']
    oorder=data['oorder']
    items=data['items']

    context = {'items': items, 'oorder': oorder, 'cartitems': cartitems}
    return render(request, 'furnapp/index.html', context)


def products(request):
    data=cartdata(request)
    cartitems=data['cartitems']
        
    products = product.objects.all()
    context = {'products': products, 'cartitems': cartitems,'msgg':'ALL PRODUCTS'}

    return render(request, 'furnapp/products.html', context)

def searchMatch(query,item):
    if query in item.description.lower() or query in item.title.lower() or query in item.category.category.lower():
        return True
    else:
        return False

def search(request):
    search=request.GET.get('search')
    data=cartdata(request)
    cartitems=data['cartitems']
    products = product.objects.all()
    prod = [item for item in products if searchMatch(search, item)]
    n=len(prod)
    if(n>0):
        context={'products':prod, 'cartitems': cartitems,'msg':''}
    else:
        context={'products':products, 'cartitems': cartitems,'msg':"Write the correct query, item not matched"}
    return render(request, 'furnapp/products.html', context)


def about(request):
    data=cartdata(request)
    cartitems=data['cartitems']
        
    context = {'cartitems': cartitems}
    return render(request, 'furnapp/about.html', context)


def contact(request):
    data=cartdata(request)
    cartitems=data['cartitems']
    form =contactform()
    if request.method=='POST':
         form =contactform(request.POST)
         if form.is_valid():
            form.save()
            

        
    context = {'cartitems': cartitems,'form':form}
    return render(request, 'furnapp/contact.html', context)


def productsdet(request, product_name):

    product_det = product.objects.get(title=product_name)
    form = commentform()
    if request.method == 'POST':
        form = commentform(request.POST)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.Product=product_det
            instance.save()
   
    
    data=cartdata(request)
    cartitems=data['cartitems']
    revi=review.objects.filter(Product=product_det.id)   

    context = {'product_det': product_det,
               'cartitems': cartitems ,'form':form,'review':revi}

    return render(request, 'furnapp/product_details.html', context)

def category(request, category_n):
    products= product.objects.filter(category=category_n)
    data=cartdata(request)
    cartitems=data['cartitems']
    msg=products[0].category
    context={'products':products,'cartitems': cartitems,'msgg':msg}
    return render(request, 'furnapp/products.html', context)


def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            
            messages.success(request, 'Account was succesfully created')
            username = form.cleaned_data['username']
            raw_password = form.cleaned_data['password1']
            user = authenticate(username=username, password=raw_password)
            custom, created = customer.objects.get_or_create(user=user)
            login(request, user)

            return render(request, 'furnapp/index.html')

    context = {'form': form}
    return render(request, 'furnapp/register.html', context)


def cart(request):
    
    data=cartdata(request)
    cartitems=data['cartitems']
    oorder=data['oorder']
    items=data['items']

    context = {'items': items, 'oorder': oorder, 'cartitems': cartitems}
    return render(request, 'furnapp/cart.html', context)


def checkout(request):
    data=cartdata(request)
    cartitems=data['cartitems']
    oorder=data['oorder']
    items=data['items']
    customer=data['customer']

    context = {'items': items, 'oorder': oorder,'cartitems': cartitems, 'customer': customer}
    return render(request, 'furnapp/checkout.html', context)


def update_item(request):
    data = json.loads(request.body)
    productid = data['productid']
    action = data['action']
    print(productid)
    print(action)
    customerr = request.user.customer
    Product = product.objects.get(id=productid)
    oorder, created = order.objects.get_or_create(customer_id=customerr,complete=False)
    orderitem, created = ordered_item.objects.get_or_create(
        order_number=oorder, product_id=Product)
    if action == 'add':
        orderitem.quantity += 1
        Product.quantity -=1
    elif action == 'remove':
        orderitem.quantity -= 1
        Product.quantity +=1
    elif action == 'add_cart':
        if(orderitem.quantity == 0):
            orderitem.quantity += 1
            Product.quantity -=1

    orderitem.save()
    Product.save()
    if orderitem.quantity <= 0:
        orderitem.delete()
    if Product.quantity <= 0:
        Product.delete()

    return JsonResponse('im here', safe=False)

def processorder(request):
    transaction_id=datetime.datetime.now().timestamp()
    data=json.loads(request.body)
    name=data['form']['name']
    email=data['form']['email']
    if request.user.is_authenticated:
        customerr = request.user.customer
        oorder, created = order.objects.get_or_create(customer_id=customerr,complete=False)
        
        customerr.name=name
        customerr.email_id=email
        customerr.save()
        
        
    else:
        customerr,oorder = guestorder(request,data)
    
    total = float(data['form']['total'])
    oorder.transaction_id=transaction_id
    if total == oorder.get_cart_total:
        oorder.complete= True
    oorder.save()
    shipping.objects.create(
		customer=customerr,
		order=oorder,
		address=data['shipping']['address'],
		city=data['shipping']['city'],
		country=data['shipping']['state'],
		zipcode=data['shipping']['zipcode'],
        contact_no=data['shipping']['contact_no']
		)

    return JsonResponse('transaction complete', safe=False)

furnapp/templates/furnapp/main.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Shop | eCommerce</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico'%}">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css'%}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css/progressbar_barfiller.css'%}">
    <link rel="stylesheet" href="{% static 'css/lightslider.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/price_rangs.css'%}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/animated-headline.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'css/slick.css'%}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">

</head>

<body>
    <!-- ? Preloader Start -->

    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'img/logo/loder.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>

    <header>
        <!-- Header Start -->
        <div class="header-area">
            <div class="main-header header-sticky">
                <div class="container-fluid">
                    <div class="row menu-wrapper align-items-center justify-content-between">
                        <div class="header-left d-flex align-items-center">
                            <!-- Logo -->
                            <div class="logo">
                                <a href="{% url 'furnapp:main'%}"><img src="{% static 'img/logo/logo.png'%}" alt=""></a>
                            </div>
                            <!-- Logo-2 -->
                            <div class="logo2">
                                <a href="{% url 'furnapp:main'%}"><img src="{% static 'img/logo/logo2.png'%}"
                                        alt=""></a>
                            </div>
                            <!-- Main-menu -->
                            <div class="main-menu d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="{%url 'furnapp:main' %}">Home</a></li>
                                        
                                            <li><a href="{%url 'furnapp:product' %}">Product</a>
                                                <ul class="submenu">
                                                    <li><a href="{%url 'furnapp:category' '1' %}">Sofa</a></li>
                                                    <li><a href="{%url 'furnapp:category' '5' %}">Table</a></li>
                                                    <li><a href="{%url 'furnapp:category' '4' %}">Chair</a></li>
                                                    <li><a href="{%url 'furnapp:category' '3' %}">Bed</a></li>
                                                    <li><a href="{%url 'furnapp:category' '6' %}">Wardrobe</a></li>
                                                    <li><a href="{%url 'furnapp:category' '7' %}">Lightning</a></li>
                                                </ul>
                                            
                                        </li>
                                        <li><a href="{% url 'furnapp:aboutus' %}">About</a></li>
                                        <li><a href="{% url 'furnapp:contact' %}">Contact</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="header-right1 d-flex align-items-center">
                            <div class="search">
                                <ul class="d-flex align-items-center">
                                    <li>
                                        <!-- Search Box -->
                                        <form method="get" action="{% url 'furnapp:search'%}" class="form-box f-right ">
                                            <input type="text" name="search" id="search" placeholder="Search products">
                                            <div class="search-icon">
                                                <i class="ti-search"></i>
                                            </div>
                                        </form>
                                    </li>
                                    <li>
                                        {% if user.is_authenticated %}
                                        <p style="margin-right: 30px !important;margin-left: 30px !important; padding-top: 20px; font-weight:bold; color: black;"> Welcome, <span style="font-weight:bold; color:#FF7F50;"> {{ user.username }}</span></p>
                                        <li><a style="margin-right: 30px !important;color: black;" href="{% url 'furnapp:logout' %}">logout</a></li>
                                        {% else %}
                                        <a href="{% url 'furnapp:login' %}" class="account-btn">My Account</a>
                                        {% endif %}
                                    </li>
                                    <li>
                                        <div class="card-stor">
                                           <a href="{% url 'furnapp:cart' %}">
                                                <img src="{% static 'img/icon/card.svg'%}" alt=""></a>
                                            <span>{{cartitems}}</span>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>

    {% block content %}



    {% endblock %}

    <!-- <footer> hai ye-->
    <div class="container-fluid" style="background-color: #000045;">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12"
                style="display: flex !important;justify-content: center !important; align-items: center !important;">
                <div class="footer-logo mb-20">
                    <br>
                    <a href="{% url 'furnapp:main'%}"><img src="{% static 'img/logo/logo2_footer.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12"
                style="display: flex !important;justify-content: center !important; align-items: center !important;">
                <div class="footer-copy-right" style="color: antiquewhite;">
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved.
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12"
                style="display: flex !important;justify-content: center !important; align-items: center !important;">
                <div class="footer-social mt-20 mb-20">
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-pinterest-p"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- </footer> -->


    <!-- Scroll Up -->
    <div id="back-top">
        <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
    </div>

    <!-- JS here -->
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js'%}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/cartt.js'%}"></script>
    <script text="text/javascript">
        var user = '{{request.user}}'
        function getToken(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getToken('csrftoken');
        function getCookie(name) {
		    // Split cookie string and get all individual name=value pairs in an array
		    var cookieArr = document.cookie.split(";");

		    // Loop through the array elements
		    for(var i = 0; i < cookieArr.length; i++) {
		        var cookiePair = cookieArr[i].split("=");

		        /* Removing whitespace at the beginning of the cookie name
		        and compare it with the given string */
		        if(name == cookiePair[0].trim()) {
		            // Decode the cookie value and return
		            return decodeURIComponent(cookiePair[1]);
		        }
		    }

		    // Return null if not found
		    return null;
		}
		var cart = JSON.parse(getCookie('cart'))

		if (cart == undefined){
			cart = {}
			console.log('Cart Created!', cart)
			document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
		}
		console.log('Cart:', cart)
        

    </script>

    <!-- Slick-slider , Owl-Carousel ,slick-nav -->
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/slick.min.js'%}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js'%}"></script>

    <!-- One Page, Animated-HeadLin, Date Picker , price, light-slider -->
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/animated.headline.js'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.js'%}"></script>
    <script src="{% static 'js/gijgo.min.js'%}"></script>

    <!-- Nice-select, sticky,Progress -->
    <script src="{% static 'js/jquery.nice-select.min.js'%}"></script>
    <script src="{% static 'js/jquery.sticky.js'%}"></script>
    <script src="{% static 'js/jquery.barfiller.js'%}"></script>

    <!-- counter , waypoint,Hover Direction -->
    <script src="{% static 'js/jquery.counterup.min.js'%}"></script>
    <script src="{% static 'js/waypoints.min.js'%} "></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/hover-direction-snake.min.js' %}"></script>

    <!-- contact js -->
    <script src="{% static 'js/contact.js'%}"></script>
    <script src="{% static 'js/jquery.form.js'%}"></script>
    <script src="{% static 'js/jquery.validate.min.js'%}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>


</body>

</html>